### PR TITLE
Add CI addon config lint

### PR DESCRIPTION
**Pull request by TheZoker**
Frenck wrote a little Github action, that lints the config file of addons:
https://github.com/frenck/action-addon-linter

This PR implements that linter via Github CI and also removes one parameter, that had the default value (according to the linter) and could therefore be removed.

The result for the first run of the CI can be seen here:
https://github.com/TheZoker/addon-hassiogooglebackup/actions/runs/549002514

### CODE REVIEW

**Comment by samccauley** [comment]
@TheZoker I appreciate you bringing Frenck's add-on linter to my attention. I've been meaning to add CI actions for my add-on.

I'm puzzled by one thing his Linter does. It seems to require that the version in the config.json file be "dev". Why would that be? Why not allow specific version numbers?

I realize it is not your linter, but Frenck's. But since you're recommending it, I thought you might be able to help me understand.

Thank you!

**Comment by TheZoker** [comment]
Hi @samccauley

Unfortunately I don't know exactly why that is. I also saw that in your commit and I'm not sure. 
Maybe @frenck can help here?

**Comment by frenck** [comment]
It only requires that is `community` is set to `true`, which isn't in this case. The linter seems to pass, right?

**Comment by samccauley** [comment]
Yeah. I found that setting after posting my question. Thank you both
for your help!

**Comment by TheZoker** [comment]
@samccauley So should I close this PR since this is implement elsewhere?

**Comment by samccauley** [comment]
@TheZoker Yeah. I'm actually going to add several linters to automatically run through github actions. They're encouraging me to do much code clean-up - which I'm doing now. Thank you for putting the idea forth. You motivated me!

**Comment by TheZoker** [comment]
Glad to hear that 🙂
Keep up the good work 👍

**Pull request closed without merging**
